// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MTNotes {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("NoteDetailController")]
	public partial class NoteDetailController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITextField __mt_titleTextField;
		
		private MonoTouch.UIKit.UITextView __mt_bodyTextView;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("titleTextField")]
		private MonoTouch.UIKit.UITextField titleTextField {
			get {
				this.__mt_titleTextField = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("titleTextField")));
				return this.__mt_titleTextField;
			}
			set {
				this.__mt_titleTextField = value;
				this.SetNativeField("titleTextField", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("bodyTextView")]
		private MonoTouch.UIKit.UITextView bodyTextView {
			get {
				this.__mt_bodyTextView = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("bodyTextView")));
				return this.__mt_bodyTextView;
			}
			set {
				this.__mt_bodyTextView = value;
				this.SetNativeField("bodyTextView", value);
			}
		}
	}
}
