// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LMT48 {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ContactDemoController")]
	public partial class ContactDemoController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_showPeoplePicker;
		
		private MonoTouch.UIKit.UIButton __mt_callPerson;
		
		private MonoTouch.UIKit.UILabel __mt_phoneLabel;
		
		private MonoTouch.UIKit.UILabel __mt_nameLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("showPeoplePicker")]
		private MonoTouch.UIKit.UIButton showPeoplePicker {
			get {
				this.__mt_showPeoplePicker = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("showPeoplePicker")));
				return this.__mt_showPeoplePicker;
			}
			set {
				this.__mt_showPeoplePicker = value;
				this.SetNativeField("showPeoplePicker", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("callPerson")]
		private MonoTouch.UIKit.UIButton callPerson {
			get {
				this.__mt_callPerson = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("callPerson")));
				return this.__mt_callPerson;
			}
			set {
				this.__mt_callPerson = value;
				this.SetNativeField("callPerson", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("phoneLabel")]
		private MonoTouch.UIKit.UILabel phoneLabel {
			get {
				this.__mt_phoneLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("phoneLabel")));
				return this.__mt_phoneLabel;
			}
			set {
				this.__mt_phoneLabel = value;
				this.SetNativeField("phoneLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("nameLabel")]
		private MonoTouch.UIKit.UILabel nameLabel {
			get {
				this.__mt_nameLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("nameLabel")));
				return this.__mt_nameLabel;
			}
			set {
				this.__mt_nameLabel = value;
				this.SetNativeField("nameLabel", value);
			}
		}
	}
}
