// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LMT12 {
    
    
    // Base type probably should be MonoTouch.Foundation.NSObject or subclass
    [MonoTouch.Foundation.Register("AppDelegate")]
    public partial class AppDelegate {
        
        private MonoTouch.UIKit.UIWindow __mt_window;
        
        private MonoTouch.UIKit.UIButton __mt_SayHelloButton;
        
        private MonoTouch.UIKit.UILabel __mt_HelloLabel;
        
        #pragma warning disable 0169
        [MonoTouch.Foundation.Connect("window")]
        private MonoTouch.UIKit.UIWindow window {
            get {
                this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
                return this.__mt_window;
            }
            set {
                this.__mt_window = value;
                this.SetNativeField("window", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("SayHelloButton")]
        private MonoTouch.UIKit.UIButton SayHelloButton {
            get {
                this.__mt_SayHelloButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("SayHelloButton")));
                return this.__mt_SayHelloButton;
            }
            set {
                this.__mt_SayHelloButton = value;
                this.SetNativeField("SayHelloButton", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("HelloLabel")]
        private MonoTouch.UIKit.UILabel HelloLabel {
            get {
                this.__mt_HelloLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("HelloLabel")));
                return this.__mt_HelloLabel;
            }
            set {
                this.__mt_HelloLabel = value;
                this.SetNativeField("HelloLabel", value);
            }
        }
    }
}
