// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LMT43 {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("DemoController")]
	public partial class DemoController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_showActivityButton;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("showActivityButton")]
		private MonoTouch.UIKit.UIButton showActivityButton {
			get {
				this.__mt_showActivityButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("showActivityButton")));
				return this.__mt_showActivityButton;
			}
			set {
				this.__mt_showActivityButton = value;
				this.SetNativeField("showActivityButton", value);
			}
		}
	}
}
