// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LMT45 {
    
    
    // Base type probably should be MonoTouch.UIKit.UIViewController or subclass
    [MonoTouch.Foundation.Register("SimpleBrowserController")]
    public partial class SimpleBrowserController {
        
        private MonoTouch.UIKit.UIView __mt_view;
        
        private MonoTouch.UIKit.UIBarButtonItem __mt_backButton;
        
        private MonoTouch.UIKit.UIBarButtonItem __mt_forwardButton;
        
        private MonoTouch.UIKit.UIBarButtonItem __mt_refreshButton;
        
        private MonoTouch.UIKit.UITextField __mt_urlTextField;
        
        private MonoTouch.UIKit.UIWebView __mt_webView;
        
        #pragma warning disable 0169
        [MonoTouch.Foundation.Connect("view")]
        private MonoTouch.UIKit.UIView view {
            get {
                this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
                return this.__mt_view;
            }
            set {
                this.__mt_view = value;
                this.SetNativeField("view", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("backButton")]
        private MonoTouch.UIKit.UIBarButtonItem backButton {
            get {
                this.__mt_backButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("backButton")));
                return this.__mt_backButton;
            }
            set {
                this.__mt_backButton = value;
                this.SetNativeField("backButton", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("forwardButton")]
        private MonoTouch.UIKit.UIBarButtonItem forwardButton {
            get {
                this.__mt_forwardButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("forwardButton")));
                return this.__mt_forwardButton;
            }
            set {
                this.__mt_forwardButton = value;
                this.SetNativeField("forwardButton", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("refreshButton")]
        private MonoTouch.UIKit.UIBarButtonItem refreshButton {
            get {
                this.__mt_refreshButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("refreshButton")));
                return this.__mt_refreshButton;
            }
            set {
                this.__mt_refreshButton = value;
                this.SetNativeField("refreshButton", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("urlTextField")]
        private MonoTouch.UIKit.UITextField urlTextField {
            get {
                this.__mt_urlTextField = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("urlTextField")));
                return this.__mt_urlTextField;
            }
            set {
                this.__mt_urlTextField = value;
                this.SetNativeField("urlTextField", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("webView")]
        private MonoTouch.UIKit.UIWebView webView {
            get {
                this.__mt_webView = ((MonoTouch.UIKit.UIWebView)(this.GetNativeField("webView")));
                return this.__mt_webView;
            }
            set {
                this.__mt_webView = value;
                this.SetNativeField("webView", value);
            }
        }
    }
}
