// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LMT92.Bing {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="BingPort", Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchOperationCompleted;
        
        public BingService() {
            this.Url = "http://api.bing.net:80/soap.asmx";
        }
        
        public BingService(string url) {
            this.Url = url;
        }
        
        public event SearchCompletedEventHandler SearchCompleted;
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/LiveSearch/2008/03/Search/Search", RequestElementName="SearchRequest", RequestNamespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search", ResponseNamespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("parameters")]
        public SearchResponse Search(SearchRequest parameters) {
            object[] results = this.Invoke("Search", new object[] {
                        parameters});
            return ((SearchResponse)(results[0]));
        }
        
        public System.IAsyncResult BeginSearch(SearchRequest parameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Search", new object[] {
                        parameters}, callback, asyncState);
        }
        
        public SearchResponse EndSearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SearchResponse)(results[0]));
        }
        
        public void SearchAsync(SearchRequest parameters) {
            this.SearchAsync(parameters, null);
        }
        
        public void SearchAsync(SearchRequest parameters, object userState) {
            if ((this.SearchOperationCompleted == null)) {
                this.SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchCompleted);
            }
            this.InvokeAsync("Search", new object[] {
                        parameters}, this.SearchOperationCompleted, userState);
        }
        
        private void OnSearchCompleted(object arg) {
            if ((this.SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCompleted(this, new SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class SearchRequest {
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue("2.2")]
        public string Version;
        
        /// <remarks/>
        public string Market;
        
        /// <remarks/>
        public string UILanguage;
        
        /// <remarks/>
        public string Query;
        
        /// <remarks/>
        public string AppId;
        
        /// <remarks/>
        public AdultOption Adult;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool AdultSpecified;
        
        /// <remarks/>
        public double Latitude;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool LatitudeSpecified;
        
        /// <remarks/>
        public double Longitude;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool LongitudeSpecified;
        
        /// <remarks/>
        public double Radius;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool RadiusSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public SearchOption[] Options;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public SourceType[] Sources;
        
        /// <remarks/>
        public WebRequest Web;
        
        /// <remarks/>
        public ImageRequest Image;
        
        /// <remarks/>
        public PhonebookRequest Phonebook;
        
        /// <remarks/>
        public VideoRequest Video;
        
        /// <remarks/>
        public NewsRequest News;
        
        /// <remarks/>
        public MobileWebRequest MobileWeb;
        
        /// <remarks/>
        public TranslationRequest Translation;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum AdultOption {
        
        /// <remarks/>
        Off,
        
        /// <remarks/>
        Moderate,
        
        /// <remarks/>
        Strict,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum SearchOption {
        
        /// <remarks/>
        DisableLocationDetection,
        
        /// <remarks/>
        EnableHighlighting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum SourceType {
        
        /// <remarks/>
        Spell,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Image,
        
        /// <remarks/>
        RelatedSearch,
        
        /// <remarks/>
        Phonebook,
        
        /// <remarks/>
        Showtimes,
        
        /// <remarks/>
        Weather,
        
        /// <remarks/>
        Video,
        
        /// <remarks/>
        Ad,
        
        /// <remarks/>
        XRank,
        
        /// <remarks/>
        InstantAnswer,
        
        /// <remarks/>
        News,
        
        /// <remarks/>
        QueryLocation,
        
        /// <remarks/>
        MobileWeb,
        
        /// <remarks/>
        Translation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class WebRequest {
        
        /// <remarks/>
        public uint Offset;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OffsetSpecified;
        
        /// <remarks/>
        public uint Count;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool CountSpecified;
        
        /// <remarks/>
        public string FileType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public WebSearchOption[] Options;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public string[] SearchTags;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum WebSearchOption {
        
        /// <remarks/>
        DisableHostCollapsing,
        
        /// <remarks/>
        DisableQueryAlterations,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class ImageRequest {
        
        /// <remarks/>
        public uint Offset;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OffsetSpecified;
        
        /// <remarks/>
        public uint Count;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool CountSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public string[] Filters;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class PhonebookRequest {
        
        /// <remarks/>
        public uint Offset;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OffsetSpecified;
        
        /// <remarks/>
        public uint Count;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool CountSpecified;
        
        /// <remarks/>
        public string FileType;
        
        /// <remarks/>
        public PhonebookSortOption SortBy;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool SortBySpecified;
        
        /// <remarks/>
        public string LocId;
        
        /// <remarks/>
        public string Category;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum PhonebookSortOption {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Relevance,
        
        /// <remarks/>
        Distance,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class VideoRequest {
        
        /// <remarks/>
        public uint Offset;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OffsetSpecified;
        
        /// <remarks/>
        public uint Count;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool CountSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public string[] Filters;
        
        /// <remarks/>
        public VideoSortOption SortBy;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool SortBySpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum VideoSortOption {
        
        /// <remarks/>
        Relevance,
        
        /// <remarks/>
        Date,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class NewsRequest {
        
        /// <remarks/>
        public uint Offset;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OffsetSpecified;
        
        /// <remarks/>
        public uint Count;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool CountSpecified;
        
        /// <remarks/>
        public string LocationOverride;
        
        /// <remarks/>
        public string Category;
        
        /// <remarks/>
        public NewsSortOption SortBy;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool SortBySpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum NewsSortOption {
        
        /// <remarks/>
        Relevance,
        
        /// <remarks/>
        Date,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class MobileWebRequest {
        
        /// <remarks/>
        public uint Offset;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OffsetSpecified;
        
        /// <remarks/>
        public uint Count;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool CountSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public MobileWebSearchOption[] Options;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public enum MobileWebSearchOption {
        
        /// <remarks/>
        DisableHostCollapsing,
        
        /// <remarks/>
        DisableQueryAlterations,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class TranslationRequest {
        
        /// <remarks/>
        public string SourceLanguage;
        
        /// <remarks/>
        public string TargetLanguage;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class SearchResponse {
        
        /// <remarks/>
        public string Version;
        
        /// <remarks/>
        public Query Query;
        
        /// <remarks/>
        public SpellResponse Spell;
        
        /// <remarks/>
        public WebResponse Web;
        
        /// <remarks/>
        public ImageResponse Image;
        
        /// <remarks/>
        public RelatedSearchResponse RelatedSearch;
        
        /// <remarks/>
        public PhonebookResponse Phonebook;
        
        /// <remarks/>
        public VideoResponse Video;
        
        /// <remarks/>
        public InstantAnswerResponse InstantAnswer;
        
        /// <remarks/>
        public NewsResponse News;
        
        /// <remarks/>
        public MobileWebResponse MobileWeb;
        
        /// <remarks/>
        public TranslationResponse Translation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public Error[] Errors;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class Query {
        
        /// <remarks/>
        public string SearchTerms;
        
        /// <remarks/>
        public string AlteredQuery;
        
        /// <remarks/>
        public string AlterationOverrideQuery;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class SpellResponse {
        
        /// <remarks/>
        public uint Total;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool TotalSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public SpellResult[] Results;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class SpellResult {
        
        /// <remarks/>
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class WebResponse {
        
        /// <remarks/>
        public uint Total;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool TotalSpecified;
        
        /// <remarks/>
        public uint Offset;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OffsetSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public WebResult[] Results;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class WebResult {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        public string CacheUrl;
        
        /// <remarks/>
        public string DisplayUrl;
        
        /// <remarks/>
        public string DateTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public WebSearchTag[] SearchTags;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public DeepLink[] DeepLinks;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class WebSearchTag {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class DeepLink {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Url;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class ImageResponse {
        
        /// <remarks/>
        public uint Total;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool TotalSpecified;
        
        /// <remarks/>
        public uint Offset;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OffsetSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public ImageResult[] Results;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class ImageResult {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string MediaUrl;
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        public string DisplayUrl;
        
        /// <remarks/>
        public uint Width;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool WidthSpecified;
        
        /// <remarks/>
        public uint Height;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool HeightSpecified;
        
        /// <remarks/>
        public uint FileSize;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool FileSizeSpecified;
        
        /// <remarks/>
        public string ContentType;
        
        /// <remarks/>
        public Thumbnail Thumbnail;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class Thumbnail {
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        public string ContentType;
        
        /// <remarks/>
        public uint Width;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool WidthSpecified;
        
        /// <remarks/>
        public uint Height;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool HeightSpecified;
        
        /// <remarks/>
        public uint FileSize;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool FileSizeSpecified;
        
        /// <remarks/>
        public uint RunTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool RunTimeSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class RelatedSearchResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public RelatedSearchResult[] Results;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class RelatedSearchResult {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Url;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class PhonebookResponse {
        
        /// <remarks/>
        public uint Total;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool TotalSpecified;
        
        /// <remarks/>
        public uint Offset;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OffsetSpecified;
        
        /// <remarks/>
        public string LocalSerpUrl;
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public PhonebookResult[] Results;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class PhonebookResult {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        public string Business;
        
        /// <remarks/>
        public string PhoneNumber;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string City;
        
        /// <remarks/>
        public string StateOrProvince;
        
        /// <remarks/>
        public string CountryOrRegion;
        
        /// <remarks/>
        public string PostalCode;
        
        /// <remarks/>
        public double Latitude;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool LatitudeSpecified;
        
        /// <remarks/>
        public double Longitude;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool LongitudeSpecified;
        
        /// <remarks/>
        public string UniqueId;
        
        /// <remarks/>
        public string BusinessUrl;
        
        /// <remarks/>
        public double UserRating;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool UserRatingSpecified;
        
        /// <remarks/>
        public uint ReviewCount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool ReviewCountSpecified;
        
        /// <remarks/>
        public string DisplayUrl;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class VideoResponse {
        
        /// <remarks/>
        public uint Total;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool TotalSpecified;
        
        /// <remarks/>
        public uint Offset;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OffsetSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public VideoResult[] Results;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class VideoResult {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string PlayUrl;
        
        /// <remarks/>
        public string SourceTitle;
        
        /// <remarks/>
        public uint RunTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool RunTimeSpecified;
        
        /// <remarks/>
        public string ClickThroughPageUrl;
        
        /// <remarks/>
        public Thumbnail StaticThumbnail;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class InstantAnswerResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public InstantAnswerResult[] Results;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class InstantAnswerResult {
        
        /// <remarks/>
        public string ContentType;
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string ClickThroughUrl;
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        public string Attribution;
        
        /// <remarks/>
        public string InstantAnswerSpecificData;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class NewsResponse {
        
        /// <remarks/>
        public uint Total;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool TotalSpecified;
        
        /// <remarks/>
        public uint Offset;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OffsetSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public NewsRelatedSearch[] RelatedSearches;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public NewsResult[] Results;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class NewsRelatedSearch {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Url;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class NewsResult {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        public string Source;
        
        /// <remarks/>
        public string Snippet;
        
        /// <remarks/>
        public string Date;
        
        /// <remarks/>
        public uint BreakingNews;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool BreakingNewsSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public NewsCollection[] NewsCollections;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class NewsCollection {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public NewsArticle[] NewsArticles;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class NewsArticle {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        public string Source;
        
        /// <remarks/>
        public string Snippet;
        
        /// <remarks/>
        public string Date;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class MobileWebResponse {
        
        /// <remarks/>
        public uint Total;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool TotalSpecified;
        
        /// <remarks/>
        public uint Offset;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool OffsetSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public MobileWebResult[] Results;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class MobileWebResult {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        public string DisplayUrl;
        
        /// <remarks/>
        public string DateTime;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class TranslationResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public TranslationResult[] Results;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class TranslationResult {
        
        /// <remarks/>
        public string TranslatedTerm;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/LiveSearch/2008/03/Search")]
    public partial class Error {
        
        /// <remarks/>
        public uint Code;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool CodeSpecified;
        
        /// <remarks/>
        public string Message;
        
        /// <remarks/>
        public string Parameter;
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public string HelpUrl;
        
        /// <remarks/>
        public string SourceType;
        
        /// <remarks/>
        public uint SourceTypeErrorCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool SourceTypeErrorCodeSpecified;
    }
    
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SearchResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void SearchCompletedEventHandler(object sender, SearchCompletedEventArgs args);
}
