// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LMT11 {
    
    
    // Base type probably should be MonoTouch.Foundation.NSObject or subclass
    [MonoTouch.Foundation.Register("AppDelegate")]
    public partial class AppDelegate {
        
        private MonoTouch.UIKit.UIWindow __mt_window;
        
        private StarViewController __mt_starViewController;
        
        #pragma warning disable 0169
        [MonoTouch.Foundation.Connect("window")]
        private MonoTouch.UIKit.UIWindow window {
            get {
                this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
                return this.__mt_window;
            }
            set {
                this.__mt_window = value;
                this.SetNativeField("window", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("starViewController")]
        private StarViewController starViewController {
            get {
                this.__mt_starViewController = ((StarViewController)(this.GetNativeField("starViewController")));
                return this.__mt_starViewController;
            }
            set {
                this.__mt_starViewController = value;
                this.SetNativeField("starViewController", value);
            }
        }
    }
}
