// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LMT11 {
    
    
    // Base type probably should be MonoTouch.UIKit.UIViewController or subclass
    [MonoTouch.Foundation.Register("StarViewController")]
    public partial class StarViewController {
        
        private StarView __mt_view;
        
        #pragma warning disable 0169
        [MonoTouch.Foundation.Connect("view")]
        private StarView view {
            get {
                this.__mt_view = ((StarView)(this.GetNativeField("view")));
                return this.__mt_view;
            }
            set {
                this.__mt_view = value;
                this.SetNativeField("view", value);
            }
        }
    }
}
