// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LMT63 {
    
    
    // Base type probably should be MonoTouch.UIKit.UIViewController or subclass
    [MonoTouch.Foundation.Register("PDFViewController")]
    public partial class PDFViewController {
        
        private PDFView __mt_view;
        
        private MonoTouch.UIKit.UIToolbar __mt_pdfToolbar;
        
        #pragma warning disable 0169
        [MonoTouch.Foundation.Connect("view")]
        private PDFView view {
            get {
                this.__mt_view = ((PDFView)(this.GetNativeField("view")));
                return this.__mt_view;
            }
            set {
                this.__mt_view = value;
                this.SetNativeField("view", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("pdfToolbar")]
        private MonoTouch.UIKit.UIToolbar pdfToolbar {
            get {
                this.__mt_pdfToolbar = ((MonoTouch.UIKit.UIToolbar)(this.GetNativeField("pdfToolbar")));
                return this.__mt_pdfToolbar;
            }
            set {
                this.__mt_pdfToolbar = value;
                this.SetNativeField("pdfToolbar", value);
            }
        }
    }
}
