// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LMT64 {
    
    
    // Base type probably should be MonoTouch.UIKit.UIViewController or subclass
    [MonoTouch.Foundation.Register("AnimationDemoViewController")]
    public partial class AnimationDemoViewController {
        
        private MonoTouch.UIKit.UIView __mt_view;
        
        private MonoTouch.UIKit.UIImageView __mt_monkeyImageView;
        
        private MonoTouch.UIKit.UIButton __mt_startAnimation;
        
        #pragma warning disable 0169
        [MonoTouch.Foundation.Connect("view")]
        private MonoTouch.UIKit.UIView view {
            get {
                this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
                return this.__mt_view;
            }
            set {
                this.__mt_view = value;
                this.SetNativeField("view", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("monkeyImageView")]
        private MonoTouch.UIKit.UIImageView monkeyImageView {
            get {
                this.__mt_monkeyImageView = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("monkeyImageView")));
                return this.__mt_monkeyImageView;
            }
            set {
                this.__mt_monkeyImageView = value;
                this.SetNativeField("monkeyImageView", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("startAnimation")]
        private MonoTouch.UIKit.UIButton startAnimation {
            get {
                this.__mt_startAnimation = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("startAnimation")));
                return this.__mt_startAnimation;
            }
            set {
                this.__mt_startAnimation = value;
                this.SetNativeField("startAnimation", value);
            }
        }
    }
}
