// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MTNotes {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ColorSelectionController")]
	public partial class ColorSelectionController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_whiteButton;
		
		private MonoTouch.UIKit.UIButton __mt_grayButton;
		
		private MonoTouch.UIKit.UIButton __mt_redButton;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("whiteButton")]
		private MonoTouch.UIKit.UIButton whiteButton {
			get {
				this.__mt_whiteButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("whiteButton")));
				return this.__mt_whiteButton;
			}
			set {
				this.__mt_whiteButton = value;
				this.SetNativeField("whiteButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("grayButton")]
		private MonoTouch.UIKit.UIButton grayButton {
			get {
				this.__mt_grayButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("grayButton")));
				return this.__mt_grayButton;
			}
			set {
				this.__mt_grayButton = value;
				this.SetNativeField("grayButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("redButton")]
		private MonoTouch.UIKit.UIButton redButton {
			get {
				this.__mt_redButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("redButton")));
				return this.__mt_redButton;
			}
			set {
				this.__mt_redButton = value;
				this.SetNativeField("redButton", value);
			}
		}
	}
}
