// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BonjourClient {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ClientViewController")]
	public partial class ClientViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITableView __mt_servicesTable;
		
		private MonoTouch.UIKit.UITextView __mt_logView;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("servicesTable")]
		private MonoTouch.UIKit.UITableView servicesTable {
			get {
				this.__mt_servicesTable = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("servicesTable")));
				return this.__mt_servicesTable;
			}
			set {
				this.__mt_servicesTable = value;
				this.SetNativeField("servicesTable", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("logView")]
		private MonoTouch.UIKit.UITextView logView {
			get {
				this.__mt_logView = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("logView")));
				return this.__mt_logView;
			}
			set {
				this.__mt_logView = value;
				this.SetNativeField("logView", value);
			}
		}
	}
}
