//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by slsvcutil, version 3.0.40818.0
// 

namespace LMT92.Bing.WCF
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "BingPortType")]
    public interface BingPortType
    {

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "x=http://schemas.microsoft.com/LiveSearch/2008/03/Search/Search", ReplyAction = "*")]
        //[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginSearch (SearchRequest1 request, System.AsyncCallback callback, object asyncState);

        SearchResponse1 EndSearch (System.IAsyncResult result);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class SearchRequest
    {

        private string versionField;

        private string marketField;

        private string uILanguageField;

        private string queryField;

        private string appIdField;

        private AdultOption adultField;

        private bool adultFieldSpecified;

        private double latitudeField;

        private bool latitudeFieldSpecified;

        private double longitudeField;

        private bool longitudeFieldSpecified;

        private double radiusField;

        private bool radiusFieldSpecified;

        private SearchOption[] optionsField;

        private SourceType[] sourcesField;

        private WebRequest webField;

        private ImageRequest imageField;

        private PhonebookRequest phonebookField;

        private VideoRequest videoField;

        private NewsRequest newsField;

        private MobileWebRequest mobileWebField;

        private TranslationRequest translationField;

        public SearchRequest ()
        {
            this.versionField = "2.2";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.ComponentModel.DefaultValueAttribute("2.2")]
        public string Version {
            get { return this.versionField; }
            set { this.versionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Market {
            get { return this.marketField; }
            set { this.marketField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string UILanguage {
            get { return this.uILanguageField; }
            set { this.uILanguageField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Query {
            get { return this.queryField; }
            set { this.queryField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string AppId {
            get { return this.appIdField; }
            set { this.appIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public AdultOption Adult {
            get { return this.adultField; }
            set { this.adultField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdultSpecified {
            get { return this.adultFieldSpecified; }
            set { this.adultFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public double Latitude {
            get { return this.latitudeField; }
            set { this.latitudeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get { return this.latitudeFieldSpecified; }
            set { this.latitudeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public double Longitude {
            get { return this.longitudeField; }
            set { this.longitudeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get { return this.longitudeFieldSpecified; }
            set { this.longitudeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public double Radius {
            get { return this.radiusField; }
            set { this.radiusField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RadiusSpecified {
            get { return this.radiusFieldSpecified; }
            set { this.radiusFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 9)]
        public SearchOption[] Options {
            get { return this.optionsField; }
            set { this.optionsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 10)]
        public SourceType[] Sources {
            get { return this.sourcesField; }
            set { this.sourcesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public WebRequest Web {
            get { return this.webField; }
            set { this.webField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public ImageRequest Image {
            get { return this.imageField; }
            set { this.imageField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public PhonebookRequest Phonebook {
            get { return this.phonebookField; }
            set { this.phonebookField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public VideoRequest Video {
            get { return this.videoField; }
            set { this.videoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public NewsRequest News {
            get { return this.newsField; }
            set { this.newsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public MobileWebRequest MobileWeb {
            get { return this.mobileWebField; }
            set { this.mobileWebField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public TranslationRequest Translation {
            get { return this.translationField; }
            set { this.translationField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public enum AdultOption
    {

        /// <remarks/>
        Off,

        /// <remarks/>
        Moderate,

        /// <remarks/>
        Strict
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public enum SearchOption
    {

        /// <remarks/>
        DisableLocationDetection,

        /// <remarks/>
        EnableHighlighting
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public enum SourceType
    {

        /// <remarks/>
        Spell,

        /// <remarks/>
        Web,

        /// <remarks/>
        Image,

        /// <remarks/>
        RelatedSearch,

        /// <remarks/>
        Phonebook,

        /// <remarks/>
        Showtimes,

        /// <remarks/>
        Weather,

        /// <remarks/>
        Video,

        /// <remarks/>
        Ad,

        /// <remarks/>
        XRank,

        /// <remarks/>
        InstantAnswer,

        /// <remarks/>
        News,

        /// <remarks/>
        QueryLocation,

        /// <remarks/>
        MobileWeb,

        /// <remarks/>
        Translation
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class WebRequest
    {

        private uint offsetField;

        private bool offsetFieldSpecified;

        private uint countField;

        private bool countFieldSpecified;

        private string fileTypeField;

        private WebSearchOption[] optionsField;

        private string[] searchTagsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Offset {
            get { return this.offsetField; }
            set { this.offsetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get { return this.offsetFieldSpecified; }
            set { this.offsetFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint Count {
            get { return this.countField; }
            set { this.countField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get { return this.countFieldSpecified; }
            set { this.countFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string FileType {
            get { return this.fileTypeField; }
            set { this.fileTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 3)]
        public WebSearchOption[] Options {
            get { return this.optionsField; }
            set { this.optionsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public string[] SearchTags {
            get { return this.searchTagsField; }
            set { this.searchTagsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public enum WebSearchOption
    {

        /// <remarks/>
        DisableHostCollapsing,

        /// <remarks/>
        DisableQueryAlterations
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class Error
    {

        private uint codeField;

        private bool codeFieldSpecified;

        private string messageField;

        private string parameterField;

        private string valueField;

        private string helpUrlField;

        private string sourceTypeField;

        private uint sourceTypeErrorCodeField;

        private bool sourceTypeErrorCodeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Code {
            get { return this.codeField; }
            set { this.codeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodeSpecified {
            get { return this.codeFieldSpecified; }
            set { this.codeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Message {
            get { return this.messageField; }
            set { this.messageField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Parameter {
            get { return this.parameterField; }
            set { this.parameterField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Value {
            get { return this.valueField; }
            set { this.valueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string HelpUrl {
            get { return this.helpUrlField; }
            set { this.helpUrlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string SourceType {
            get { return this.sourceTypeField; }
            set { this.sourceTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public uint SourceTypeErrorCode {
            get { return this.sourceTypeErrorCodeField; }
            set { this.sourceTypeErrorCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceTypeErrorCodeSpecified {
            get { return this.sourceTypeErrorCodeFieldSpecified; }
            set { this.sourceTypeErrorCodeFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class TranslationResult
    {

        private string translatedTermField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string TranslatedTerm {
            get { return this.translatedTermField; }
            set { this.translatedTermField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class TranslationResponse
    {

        private TranslationResult[] resultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public TranslationResult[] Results {
            get { return this.resultsField; }
            set { this.resultsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class MobileWebResult
    {

        private string titleField;

        private string descriptionField;

        private string urlField;

        private string displayUrlField;

        private string dateTimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Title {
            get { return this.titleField; }
            set { this.titleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Description {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Url {
            get { return this.urlField; }
            set { this.urlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string DisplayUrl {
            get { return this.displayUrlField; }
            set { this.displayUrlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string DateTime {
            get { return this.dateTimeField; }
            set { this.dateTimeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class MobileWebResponse
    {

        private uint totalField;

        private bool totalFieldSpecified;

        private uint offsetField;

        private bool offsetFieldSpecified;

        private MobileWebResult[] resultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Total {
            get { return this.totalField; }
            set { this.totalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get { return this.totalFieldSpecified; }
            set { this.totalFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint Offset {
            get { return this.offsetField; }
            set { this.offsetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get { return this.offsetFieldSpecified; }
            set { this.offsetFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public MobileWebResult[] Results {
            get { return this.resultsField; }
            set { this.resultsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class NewsArticle
    {

        private string titleField;

        private string urlField;

        private string sourceField;

        private string snippetField;

        private string dateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Title {
            get { return this.titleField; }
            set { this.titleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Url {
            get { return this.urlField; }
            set { this.urlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Source {
            get { return this.sourceField; }
            set { this.sourceField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Snippet {
            get { return this.snippetField; }
            set { this.snippetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Date {
            get { return this.dateField; }
            set { this.dateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class NewsCollection
    {

        private string nameField;

        private NewsArticle[] newsArticlesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Name {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public NewsArticle[] NewsArticles {
            get { return this.newsArticlesField; }
            set { this.newsArticlesField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class NewsResult
    {

        private string titleField;

        private string urlField;

        private string sourceField;

        private string snippetField;

        private string dateField;

        private uint breakingNewsField;

        private bool breakingNewsFieldSpecified;

        private NewsCollection[] newsCollectionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Title {
            get { return this.titleField; }
            set { this.titleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Url {
            get { return this.urlField; }
            set { this.urlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Source {
            get { return this.sourceField; }
            set { this.sourceField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Snippet {
            get { return this.snippetField; }
            set { this.snippetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Date {
            get { return this.dateField; }
            set { this.dateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public uint BreakingNews {
            get { return this.breakingNewsField; }
            set { this.breakingNewsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BreakingNewsSpecified {
            get { return this.breakingNewsFieldSpecified; }
            set { this.breakingNewsFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 6)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public NewsCollection[] NewsCollections {
            get { return this.newsCollectionsField; }
            set { this.newsCollectionsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class NewsRelatedSearch
    {

        private string titleField;

        private string urlField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Title {
            get { return this.titleField; }
            set { this.titleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Url {
            get { return this.urlField; }
            set { this.urlField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class NewsResponse
    {

        private uint totalField;

        private bool totalFieldSpecified;

        private uint offsetField;

        private bool offsetFieldSpecified;

        private NewsRelatedSearch[] relatedSearchesField;

        private NewsResult[] resultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Total {
            get { return this.totalField; }
            set { this.totalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get { return this.totalFieldSpecified; }
            set { this.totalFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint Offset {
            get { return this.offsetField; }
            set { this.offsetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get { return this.offsetFieldSpecified; }
            set { this.offsetFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public NewsRelatedSearch[] RelatedSearches {
            get { return this.relatedSearchesField; }
            set { this.relatedSearchesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public NewsResult[] Results {
            get { return this.resultsField; }
            set { this.resultsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class InstantAnswerResult
    {

        private string contentTypeField;

        private string titleField;

        private string clickThroughUrlField;

        private string urlField;

        private string attributionField;

        private string instantAnswerSpecificDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string ContentType {
            get { return this.contentTypeField; }
            set { this.contentTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Title {
            get { return this.titleField; }
            set { this.titleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ClickThroughUrl {
            get { return this.clickThroughUrlField; }
            set { this.clickThroughUrlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Url {
            get { return this.urlField; }
            set { this.urlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Attribution {
            get { return this.attributionField; }
            set { this.attributionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string InstantAnswerSpecificData {
            get { return this.instantAnswerSpecificDataField; }
            set { this.instantAnswerSpecificDataField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class InstantAnswerResponse
    {

        private InstantAnswerResult[] resultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public InstantAnswerResult[] Results {
            get { return this.resultsField; }
            set { this.resultsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class VideoResult
    {

        private string titleField;

        private string playUrlField;

        private string sourceTitleField;

        private uint runTimeField;

        private bool runTimeFieldSpecified;

        private string clickThroughPageUrlField;

        private Thumbnail staticThumbnailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Title {
            get { return this.titleField; }
            set { this.titleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string PlayUrl {
            get { return this.playUrlField; }
            set { this.playUrlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string SourceTitle {
            get { return this.sourceTitleField; }
            set { this.sourceTitleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public uint RunTime {
            get { return this.runTimeField; }
            set { this.runTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RunTimeSpecified {
            get { return this.runTimeFieldSpecified; }
            set { this.runTimeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string ClickThroughPageUrl {
            get { return this.clickThroughPageUrlField; }
            set { this.clickThroughPageUrlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public Thumbnail StaticThumbnail {
            get { return this.staticThumbnailField; }
            set { this.staticThumbnailField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class Thumbnail
    {

        private string urlField;

        private string contentTypeField;

        private uint widthField;

        private bool widthFieldSpecified;

        private uint heightField;

        private bool heightFieldSpecified;

        private uint fileSizeField;

        private bool fileSizeFieldSpecified;

        private uint runTimeField;

        private bool runTimeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Url {
            get { return this.urlField; }
            set { this.urlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ContentType {
            get { return this.contentTypeField; }
            set { this.contentTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public uint Width {
            get { return this.widthField; }
            set { this.widthField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get { return this.widthFieldSpecified; }
            set { this.widthFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public uint Height {
            get { return this.heightField; }
            set { this.heightField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get { return this.heightFieldSpecified; }
            set { this.heightFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public uint FileSize {
            get { return this.fileSizeField; }
            set { this.fileSizeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileSizeSpecified {
            get { return this.fileSizeFieldSpecified; }
            set { this.fileSizeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public uint RunTime {
            get { return this.runTimeField; }
            set { this.runTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RunTimeSpecified {
            get { return this.runTimeFieldSpecified; }
            set { this.runTimeFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class VideoResponse
    {

        private uint totalField;

        private bool totalFieldSpecified;

        private uint offsetField;

        private bool offsetFieldSpecified;

        private VideoResult[] resultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Total {
            get { return this.totalField; }
            set { this.totalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get { return this.totalFieldSpecified; }
            set { this.totalFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint Offset {
            get { return this.offsetField; }
            set { this.offsetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get { return this.offsetFieldSpecified; }
            set { this.offsetFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public VideoResult[] Results {
            get { return this.resultsField; }
            set { this.resultsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class PhonebookResult
    {

        private string titleField;

        private string urlField;

        private string businessField;

        private string phoneNumberField;

        private string addressField;

        private string cityField;

        private string stateOrProvinceField;

        private string countryOrRegionField;

        private string postalCodeField;

        private double latitudeField;

        private bool latitudeFieldSpecified;

        private double longitudeField;

        private bool longitudeFieldSpecified;

        private string uniqueIdField;

        private string businessUrlField;

        private double userRatingField;

        private bool userRatingFieldSpecified;

        private uint reviewCountField;

        private bool reviewCountFieldSpecified;

        private string displayUrlField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Title {
            get { return this.titleField; }
            set { this.titleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Url {
            get { return this.urlField; }
            set { this.urlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Business {
            get { return this.businessField; }
            set { this.businessField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string PhoneNumber {
            get { return this.phoneNumberField; }
            set { this.phoneNumberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Address {
            get { return this.addressField; }
            set { this.addressField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string City {
            get { return this.cityField; }
            set { this.cityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string StateOrProvince {
            get { return this.stateOrProvinceField; }
            set { this.stateOrProvinceField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string CountryOrRegion {
            get { return this.countryOrRegionField; }
            set { this.countryOrRegionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string PostalCode {
            get { return this.postalCodeField; }
            set { this.postalCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public double Latitude {
            get { return this.latitudeField; }
            set { this.latitudeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get { return this.latitudeFieldSpecified; }
            set { this.latitudeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public double Longitude {
            get { return this.longitudeField; }
            set { this.longitudeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get { return this.longitudeFieldSpecified; }
            set { this.longitudeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string UniqueId {
            get { return this.uniqueIdField; }
            set { this.uniqueIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string BusinessUrl {
            get { return this.businessUrlField; }
            set { this.businessUrlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public double UserRating {
            get { return this.userRatingField; }
            set { this.userRatingField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserRatingSpecified {
            get { return this.userRatingFieldSpecified; }
            set { this.userRatingFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public uint ReviewCount {
            get { return this.reviewCountField; }
            set { this.reviewCountField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReviewCountSpecified {
            get { return this.reviewCountFieldSpecified; }
            set { this.reviewCountFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string DisplayUrl {
            get { return this.displayUrlField; }
            set { this.displayUrlField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class PhonebookResponse
    {

        private uint totalField;

        private bool totalFieldSpecified;

        private uint offsetField;

        private bool offsetFieldSpecified;

        private string localSerpUrlField;

        private string titleField;

        private PhonebookResult[] resultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Total {
            get { return this.totalField; }
            set { this.totalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get { return this.totalFieldSpecified; }
            set { this.totalFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint Offset {
            get { return this.offsetField; }
            set { this.offsetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get { return this.offsetFieldSpecified; }
            set { this.offsetFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string LocalSerpUrl {
            get { return this.localSerpUrlField; }
            set { this.localSerpUrlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Title {
            get { return this.titleField; }
            set { this.titleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public PhonebookResult[] Results {
            get { return this.resultsField; }
            set { this.resultsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class RelatedSearchResult
    {

        private string titleField;

        private string urlField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Title {
            get { return this.titleField; }
            set { this.titleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Url {
            get { return this.urlField; }
            set { this.urlField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class RelatedSearchResponse
    {

        private RelatedSearchResult[] resultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public RelatedSearchResult[] Results {
            get { return this.resultsField; }
            set { this.resultsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class ImageResult
    {

        private string titleField;

        private string mediaUrlField;

        private string urlField;

        private string displayUrlField;

        private uint widthField;

        private bool widthFieldSpecified;

        private uint heightField;

        private bool heightFieldSpecified;

        private uint fileSizeField;

        private bool fileSizeFieldSpecified;

        private string contentTypeField;

        private Thumbnail thumbnailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Title {
            get { return this.titleField; }
            set { this.titleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string MediaUrl {
            get { return this.mediaUrlField; }
            set { this.mediaUrlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Url {
            get { return this.urlField; }
            set { this.urlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string DisplayUrl {
            get { return this.displayUrlField; }
            set { this.displayUrlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public uint Width {
            get { return this.widthField; }
            set { this.widthField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get { return this.widthFieldSpecified; }
            set { this.widthFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public uint Height {
            get { return this.heightField; }
            set { this.heightField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get { return this.heightFieldSpecified; }
            set { this.heightFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public uint FileSize {
            get { return this.fileSizeField; }
            set { this.fileSizeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileSizeSpecified {
            get { return this.fileSizeFieldSpecified; }
            set { this.fileSizeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string ContentType {
            get { return this.contentTypeField; }
            set { this.contentTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public Thumbnail Thumbnail {
            get { return this.thumbnailField; }
            set { this.thumbnailField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class ImageResponse
    {

        private uint totalField;

        private bool totalFieldSpecified;

        private uint offsetField;

        private bool offsetFieldSpecified;

        private ImageResult[] resultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Total {
            get { return this.totalField; }
            set { this.totalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get { return this.totalFieldSpecified; }
            set { this.totalFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint Offset {
            get { return this.offsetField; }
            set { this.offsetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get { return this.offsetFieldSpecified; }
            set { this.offsetFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public ImageResult[] Results {
            get { return this.resultsField; }
            set { this.resultsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class DeepLink
    {

        private string titleField;

        private string urlField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Title {
            get { return this.titleField; }
            set { this.titleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Url {
            get { return this.urlField; }
            set { this.urlField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class WebSearchTag
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Name {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Value {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class WebResult
    {

        private string titleField;

        private string descriptionField;

        private string urlField;

        private string cacheUrlField;

        private string displayUrlField;

        private string dateTimeField;

        private WebSearchTag[] searchTagsField;

        private DeepLink[] deepLinksField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Title {
            get { return this.titleField; }
            set { this.titleField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Description {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Url {
            get { return this.urlField; }
            set { this.urlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string CacheUrl {
            get { return this.cacheUrlField; }
            set { this.cacheUrlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string DisplayUrl {
            get { return this.displayUrlField; }
            set { this.displayUrlField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string DateTime {
            get { return this.dateTimeField; }
            set { this.dateTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 6)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public WebSearchTag[] SearchTags {
            get { return this.searchTagsField; }
            set { this.searchTagsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 7)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public DeepLink[] DeepLinks {
            get { return this.deepLinksField; }
            set { this.deepLinksField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class WebResponse
    {

        private uint totalField;

        private bool totalFieldSpecified;

        private uint offsetField;

        private bool offsetFieldSpecified;

        private WebResult[] resultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Total {
            get { return this.totalField; }
            set { this.totalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get { return this.totalFieldSpecified; }
            set { this.totalFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint Offset {
            get { return this.offsetField; }
            set { this.offsetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get { return this.offsetFieldSpecified; }
            set { this.offsetFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public WebResult[] Results {
            get { return this.resultsField; }
            set { this.resultsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class SpellResult
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Value {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class SpellResponse
    {

        private uint totalField;

        private bool totalFieldSpecified;

        private SpellResult[] resultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Total {
            get { return this.totalField; }
            set { this.totalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSpecified {
            get { return this.totalFieldSpecified; }
            set { this.totalFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public SpellResult[] Results {
            get { return this.resultsField; }
            set { this.resultsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class Query
    {

        private string searchTermsField;

        private string alteredQueryField;

        private string alterationOverrideQueryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string SearchTerms {
            get { return this.searchTermsField; }
            set { this.searchTermsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string AlteredQuery {
            get { return this.alteredQueryField; }
            set { this.alteredQueryField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string AlterationOverrideQuery {
            get { return this.alterationOverrideQueryField; }
            set { this.alterationOverrideQueryField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class SearchResponse
    {

        private string versionField;

        private Query queryField;

        private SpellResponse spellField;

        private WebResponse webField;

        private ImageResponse imageField;

        private RelatedSearchResponse relatedSearchField;

        private PhonebookResponse phonebookField;

        private VideoResponse videoField;

        private InstantAnswerResponse instantAnswerField;

        private NewsResponse newsField;

        private MobileWebResponse mobileWebField;

        private TranslationResponse translationField;

        private Error[] errorsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Version {
            get { return this.versionField; }
            set { this.versionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public Query Query {
            get { return this.queryField; }
            set { this.queryField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public SpellResponse Spell {
            get { return this.spellField; }
            set { this.spellField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public WebResponse Web {
            get { return this.webField; }
            set { this.webField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public ImageResponse Image {
            get { return this.imageField; }
            set { this.imageField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public RelatedSearchResponse RelatedSearch {
            get { return this.relatedSearchField; }
            set { this.relatedSearchField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public PhonebookResponse Phonebook {
            get { return this.phonebookField; }
            set { this.phonebookField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public VideoResponse Video {
            get { return this.videoField; }
            set { this.videoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public InstantAnswerResponse InstantAnswer {
            get { return this.instantAnswerField; }
            set { this.instantAnswerField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public NewsResponse News {
            get { return this.newsField; }
            set { this.newsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public MobileWebResponse MobileWeb {
            get { return this.mobileWebField; }
            set { this.mobileWebField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public TranslationResponse Translation {
            get { return this.translationField; }
            set { this.translationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 12)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Error[] Errors {
            get { return this.errorsField; }
            set { this.errorsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class TranslationRequest
    {

        private string sourceLanguageField;

        private string targetLanguageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string SourceLanguage {
            get { return this.sourceLanguageField; }
            set { this.sourceLanguageField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string TargetLanguage {
            get { return this.targetLanguageField; }
            set { this.targetLanguageField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class MobileWebRequest
    {

        private uint offsetField;

        private bool offsetFieldSpecified;

        private uint countField;

        private bool countFieldSpecified;

        private MobileWebSearchOption[] optionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Offset {
            get { return this.offsetField; }
            set { this.offsetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get { return this.offsetFieldSpecified; }
            set { this.offsetFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint Count {
            get { return this.countField; }
            set { this.countField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get { return this.countFieldSpecified; }
            set { this.countFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        public MobileWebSearchOption[] Options {
            get { return this.optionsField; }
            set { this.optionsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public enum MobileWebSearchOption
    {

        /// <remarks/>
        DisableHostCollapsing,

        /// <remarks/>
        DisableQueryAlterations
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class NewsRequest
    {

        private uint offsetField;

        private bool offsetFieldSpecified;

        private uint countField;

        private bool countFieldSpecified;

        private string locationOverrideField;

        private string categoryField;

        private NewsSortOption sortByField;

        private bool sortByFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Offset {
            get { return this.offsetField; }
            set { this.offsetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get { return this.offsetFieldSpecified; }
            set { this.offsetFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint Count {
            get { return this.countField; }
            set { this.countField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get { return this.countFieldSpecified; }
            set { this.countFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string LocationOverride {
            get { return this.locationOverrideField; }
            set { this.locationOverrideField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Category {
            get { return this.categoryField; }
            set { this.categoryField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public NewsSortOption SortBy {
            get { return this.sortByField; }
            set { this.sortByField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortBySpecified {
            get { return this.sortByFieldSpecified; }
            set { this.sortByFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public enum NewsSortOption
    {

        /// <remarks/>
        Relevance,

        /// <remarks/>
        Date
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class VideoRequest
    {

        private uint offsetField;

        private bool offsetFieldSpecified;

        private uint countField;

        private bool countFieldSpecified;

        private string[] filtersField;

        private VideoSortOption sortByField;

        private bool sortByFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Offset {
            get { return this.offsetField; }
            set { this.offsetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get { return this.offsetFieldSpecified; }
            set { this.offsetFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint Count {
            get { return this.countField; }
            set { this.countField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get { return this.countFieldSpecified; }
            set { this.countFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public string[] Filters {
            get { return this.filtersField; }
            set { this.filtersField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public VideoSortOption SortBy {
            get { return this.sortByField; }
            set { this.sortByField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortBySpecified {
            get { return this.sortByFieldSpecified; }
            set { this.sortByFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public enum VideoSortOption
    {

        /// <remarks/>
        Relevance,

        /// <remarks/>
        Date
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class PhonebookRequest
    {

        private uint offsetField;

        private bool offsetFieldSpecified;

        private uint countField;

        private bool countFieldSpecified;

        private string fileTypeField;

        private PhonebookSortOption sortByField;

        private bool sortByFieldSpecified;

        private string locIdField;

        private string categoryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Offset {
            get { return this.offsetField; }
            set { this.offsetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get { return this.offsetFieldSpecified; }
            set { this.offsetFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint Count {
            get { return this.countField; }
            set { this.countField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get { return this.countFieldSpecified; }
            set { this.countFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string FileType {
            get { return this.fileTypeField; }
            set { this.fileTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public PhonebookSortOption SortBy {
            get { return this.sortByField; }
            set { this.sortByField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortBySpecified {
            get { return this.sortByFieldSpecified; }
            set { this.sortByFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string LocId {
            get { return this.locIdField; }
            set { this.locIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string Category {
            get { return this.categoryField; }
            set { this.categoryField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public enum PhonebookSortOption
    {

        /// <remarks/>
        Default,

        /// <remarks/>
        Relevance,

        /// <remarks/>
        Distance
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("slsvcutil", "3.0.40818.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute()]
    public partial class ImageRequest
    {

        private uint offsetField;

        private bool offsetFieldSpecified;

        private uint countField;

        private bool countFieldSpecified;

        private string[] filtersField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public uint Offset {
            get { return this.offsetField; }
            set { this.offsetField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffsetSpecified {
            get { return this.offsetFieldSpecified; }
            set { this.offsetFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public uint Count {
            get { return this.countField; }
            set { this.countField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get { return this.countFieldSpecified; }
            set { this.countFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public string[] Filters {
            get { return this.filtersField; }
            set { this.filtersField = value; }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SearchRequest1
    {

        // [System.ServiceModel.MessageBodyMemberAttribute(, Order=0)]
        public SearchRequest parameters;

        public SearchRequest1 ()
        {
        }

        public SearchRequest1 (SearchRequest parameters)
        {
            this.parameters = parameters;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SearchResponse1
    {


        public SearchResponse parameters;

        public SearchResponse1 ()
        {
        }

        public SearchResponse1 (SearchResponse parameters)
        {
            this.parameters = parameters;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface BingPortTypeChannel : BingPortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public SearchCompletedEventArgs (object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public SearchResponse Result {
            get {
                base.RaiseExceptionIfNecessary ();
                return ((SearchResponse)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class BingPortTypeClient : System.ServiceModel.ClientBase<BingPortType>, BingPortType
    {

        private BeginOperationDelegate onBeginSearchDelegate;

        private EndOperationDelegate onEndSearchDelegate;

        private System.Threading.SendOrPostCallback onSearchCompletedDelegate;

        private BeginOperationDelegate onBeginOpenDelegate;

        private EndOperationDelegate onEndOpenDelegate;

        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;

        private BeginOperationDelegate onBeginCloseDelegate;

        private EndOperationDelegate onEndCloseDelegate;

        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;

        public BingPortTypeClient ()
        {
        }

        public BingPortTypeClient (string endpointConfigurationName) : base(endpointConfigurationName)
        {
        }

        public BingPortTypeClient (string endpointConfigurationName, string remoteAddress) : base(endpointConfigurationName, remoteAddress)
        {
        }

        public BingPortTypeClient (string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : base(endpointConfigurationName, remoteAddress)
        {
        }

        public BingPortTypeClient (System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : base(binding, remoteAddress)
        {
        }

        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager> ();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                } else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager> ();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                } else {
                    throw new System.InvalidOperationException ("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" + "ookieContainerBindingElement.");
                }
            }
        }

        public event System.EventHandler<SearchCompletedEventArgs> SearchCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BingPortType.BeginSearch (SearchRequest1 request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginSearch (request, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSearch (SearchRequest parameters, System.AsyncCallback callback, object asyncState)
        {
            SearchRequest1 inValue = new SearchRequest1 ();
            inValue.parameters = parameters;
            return ((BingPortType)(this)).BeginSearch (inValue, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchResponse1 BingPortType.EndSearch (System.IAsyncResult result)
        {
            return base.Channel.EndSearch (result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private SearchResponse EndSearch (System.IAsyncResult result)
        {
            SearchResponse1 retVal = ((BingPortType)(this)).EndSearch (result);
            return retVal.parameters;
        }

        private System.IAsyncResult OnBeginSearch (object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            SearchRequest parameters = ((SearchRequest)(inValues[0]));
            return this.BeginSearch (parameters, callback, asyncState);
        }

        private object[] OnEndSearch (System.IAsyncResult result)
        {
            SearchResponse retVal = this.EndSearch (result);
            return new object[] { retVal };
        }

        private void OnSearchCompleted (object state)
        {
            if ((this.SearchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchCompleted (this, new SearchCompletedEventArgs (e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void SearchAsync (SearchRequest parameters)
        {
            this.SearchAsync (parameters, null);
        }

        public void SearchAsync (SearchRequest parameters, object userState)
        {
            if ((this.onBeginSearchDelegate == null)) {
                this.onBeginSearchDelegate = new BeginOperationDelegate (this.OnBeginSearch);
            }
            if ((this.onEndSearchDelegate == null)) {
                this.onEndSearchDelegate = new EndOperationDelegate (this.OnEndSearch);
            }
            if ((this.onSearchCompletedDelegate == null)) {
                this.onSearchCompletedDelegate = new System.Threading.SendOrPostCallback (this.OnSearchCompleted);
            }
            base.InvokeAsync (this.onBeginSearchDelegate, new object[] { parameters }, this.onEndSearchDelegate, this.onSearchCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginOpen (object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen (callback, asyncState);
        }

        private object[] OnEndOpen (System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen (result);
            return null;
        }

        private void OnOpenCompleted (object state)
        {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted (this, new System.ComponentModel.AsyncCompletedEventArgs (e.Error, e.Cancelled, e.UserState));
            }
        }

        public void OpenAsync ()
        {
            this.OpenAsync (null);
        }

        public void OpenAsync (object userState)
        {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate (this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate (this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback (this.OnOpenCompleted);
            }
            base.InvokeAsync (this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginClose (object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose (callback, asyncState);
        }

        private object[] OnEndClose (System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose (result);
            return null;
        }

        private void OnCloseCompleted (object state)
        {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted (this, new System.ComponentModel.AsyncCompletedEventArgs (e.Error, e.Cancelled, e.UserState));
            }
        }

        public void CloseAsync ()
        {
            this.CloseAsync (null);
        }

        public void CloseAsync (object userState)
        {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate (this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate (this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback (this.OnCloseCompleted);
            }
            base.InvokeAsync (this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }

        protected override BingPortType CreateChannel ()
        {
            return new BingPortTypeClientChannel (this);
        }

        private class BingPortTypeClientChannel : ChannelBase<BingPortType>, BingPortType
        {

            public BingPortTypeClientChannel (System.ServiceModel.ClientBase<BingPortType> client) : base(client)
            {
            }

            public System.IAsyncResult BeginSearch (SearchRequest1 request, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke ("Search", _args, callback, asyncState);
                return _result;
            }

            public SearchResponse1 EndSearch (System.IAsyncResult result)
            {
                object[] _args = new object[0];
                SearchResponse1 _result = ((SearchResponse1)(base.EndInvoke ("Search", _args, result)));
                return _result;
            }
        }
    }
}
