// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LMT62 {
    
    
    // Base type probably should be MonoTouch.UIKit.UIViewController or subclass
    [MonoTouch.Foundation.Register("CustomImageViewController")]
    public partial class CustomImageViewController {
        
        private CustomImageView __mt_view;
        
        private MonoTouch.UIKit.UIButton __mt_addBanana;
        
        private MonoTouch.UIKit.UIImageView __mt_iv;
        
        #pragma warning disable 0169
        [MonoTouch.Foundation.Connect("view")]
        private CustomImageView view {
            get {
                this.__mt_view = ((CustomImageView)(this.GetNativeField("view")));
                return this.__mt_view;
            }
            set {
                this.__mt_view = value;
                this.SetNativeField("view", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("addBanana")]
        private MonoTouch.UIKit.UIButton addBanana {
            get {
                this.__mt_addBanana = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("addBanana")));
                return this.__mt_addBanana;
            }
            set {
                this.__mt_addBanana = value;
                this.SetNativeField("addBanana", value);
            }
        }
        
        [MonoTouch.Foundation.Connect("iv")]
        private MonoTouch.UIKit.UIImageView iv {
            get {
                this.__mt_iv = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("iv")));
                return this.__mt_iv;
            }
            set {
                this.__mt_iv = value;
                this.SetNativeField("iv", value);
            }
        }
    }
}
